name: data-imputation-paper
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8.*
  - pip
  - numpy
  - scipy
  - pandas
  - ipython
  - matplotlib
  - seaborn
  - scikit-learn>=0.24
  - optuna
  # for development only (could also be kept in a separate environment file)
  - pip:
    - flake8
    - autokeras
    - flake8-mypy
    - pydocstyle
    - tensorflow
    - openml
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - sphinx
  - recommonmark
